name: Go
# переменная среда
env:
  APPLICATION_NAME: "Go"
  PACKAGE_NAME: "Main-${{ github.sha }}"
# Чтобы сработали job в каких событиях?
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
 # Первый job 
 testing:
  # Docker image где будет стартовать событие
  runs-on: ubuntu-latest
  # Какие шаги должен сделать наш контейнер
  steps:
  - name: Print Hello Message
    run: echo "Hello World from testing job"
  - name: Show env
    run: echo "application ${{ env.APPLICATION_NAME }}"
  - name: List current folder
    run: ls -la
 # Второй job  
 deploy:
  runs-on: ubuntu-latest
  # ожидать контейнер testing
  needs: [testing]
  steps:
  - name: Print Hello Message
    run: echo "Hello World from deploy job"
  - name: Show env
    run: echo "package application ${{ env.PACKAGE_NAME }}"