name: Go
# переменная среда
env:
  APPLICATION_NAME: "Go"
  PACKAGE_NAME: "Main-${{ github.sha }}"
# Чтобы сработали job в каких событиях?
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
 # Первый job 
 testing:
  # Docker image где будет стартовать событие
  runs-on: ubuntu-latest
  # Какие шаги должен сделать наш контейнер
  steps:
  - name: Print Hello Message
    run: echo "Hello World from testing job"
  - name: Show env
    run: echo "application ${{ env.APPLICATION_NAME }}"
  - name: List current folder after
    run: ls -la
  - name: Git Clone repository
    # клонировать в репозиторий 
    uses: actions/checkout@v1
  - name: List current folder before
    run: ls -la
 # Второй job  
 deploy:
  runs-on: ubuntu-latest
  # ожидать контейнер testing
  needs: [testing]
  env:
    JOB_ENV: "testing job"
  steps:
  - name: Print Hello Message
    run: echo "Hello World from deploy job"
  - name: JOB ENV and Step ENV
    run: |
     echo job " ${{ env.JOB_ENV }} "
     echo step " $LOCAL_ENV"
    env:
     LOCAL_ENV: "testing step env"
  - name: Show env
    run: echo "package application ${{ env.PACKAGE_NAME }}"
  - name: Lets test command
    run: aws --version